"""Workstation secrets-loader drift-check contracts.

Regression cover for the 2026-08-13 incident: the workstation `taylo` ran a
loader that no committed source generates. It read snake_case Graph keys from a
camelCase secret (every Graph variable empty) and reintroduced the `~/.aws`
credential-file fallback banned by TASK-756.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "check-workstation-loader-drift.py"

GENERATED_HEADER = "# Generated by scripts/bootstrap-windows-secrets.py — do not commit"

# Shape the committed generator emits.
GOOD_LOADER = f"""\
# Machine-local secrets loader for PLX agent workstations
{GENERATED_HEADER}
#
# MICROSOFT_GRAPH_TENANT_ID / _CLIENT_ID / _CLIENT_SECRET:
#   matched set from plx/prod/m365/cursor-graph/v1 (PLX_Cursor_Graph).
#   Do not substitute prod/ec2-secrets Graph keys (different app).

$env:GITHUB_TOKEN = 'x'

try {{
  $__graph = & $__awsCli secretsmanager get-secret-value --region us-east-1 \
--secret-id plx/prod/m365/cursor-graph/v1 --query SecretString --output text | ConvertFrom-Json
  if (-not $__graph.clientSecret) {{ throw 'secret payload missing clientSecret' }}
  $env:MICROSOFT_GRAPH_TENANT_ID     = $__graph.tenantId
  $env:MICROSOFT_GRAPH_CLIENT_ID     = $__graph.clientId
  $env:MICROSOFT_GRAPH_CLIENT_SECRET = $__graph.clientSecret
}} catch {{
  Write-Warning "Graph credential unavailable"
}}
"""

# The real rogue loader found on `taylo`, reduced to its defects.
ROGUE_LOADER = """\
# Machine-local secrets loader for PLX agent workstations
# Generated by PLX_MC setup - do not commit

function Read-SecretFile([string]$Name) {
  $p = Join-Path $HOME ".aws/$Name"
  if (Test-Path $p) { return (Get-Content $p -Raw).Trim() }
  return ""
}

function Set-PlxCursorGraphFromAws {
  $blob = Get-PlxAwsSecretJson 'plx/prod/m365/cursor-graph/v1'
  $tenant = $blob.MICROSOFT_GRAPH_TENANT_ID
  if (-not $tenant) { $tenant = $blob.tenant_id }
  $client = $blob.MICROSOFT_GRAPH_CLIENT_ID
  if (-not $client) { $client = $blob.client_id }
  $secret = $blob.MICROSOFT_GRAPH_CLIENT_SECRET
  if (-not $secret) { $secret = $blob.client_secret }
}

$env:GITHUB_TOKEN = (Get-Content "$HOME\\.aws\\GHUB_DELLLAPTOP_KEY.txt" -Raw).Trim()
"""


def load_script() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "check_workstation_loader_drift", SCRIPT
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def run_on(tmp_path: Path, content: str) -> int:
    check = load_script()
    loader = tmp_path / ".secrets-env.staging.ps1"
    loader.write_text(content, encoding="utf-8")
    argv = sys.argv
    sys.argv = ["check-workstation-loader-drift.py", "--loader", str(loader)]
    try:
        return check.main()
    finally:
        sys.argv = argv


def test_generated_loader_passes(tmp_path: Path) -> None:
    assert run_on(tmp_path, GOOD_LOADER) == 0


def test_rogue_loader_is_rejected(tmp_path: Path) -> None:
    assert run_on(tmp_path, ROGUE_LOADER) == 1


def test_missing_loader_skips(tmp_path: Path) -> None:
    check = load_script()
    argv = sys.argv
    sys.argv = [
        "check-workstation-loader-drift.py",
        "--loader",
        str(tmp_path / "absent.ps1"),
    ]
    try:
        assert check.main() == 2
    finally:
        sys.argv = argv


def test_documented_ec2_secrets_rule_is_not_a_finding(tmp_path: Path) -> None:
    """The generator documents the ec2-secrets rule in a comment.

    A substring scan flags that correct file. Only executable lines count.
    """
    check = load_script()
    findings: list[str] = []
    code = check.strip_comments(GOOD_LOADER)
    check.check_matched_set(code, findings)
    assert findings == []


@pytest.mark.parametrize("spelling", ["tenant_id", "client_id", "client_secret"])
def test_snake_case_graph_keys_are_rejected(tmp_path: Path, spelling: str) -> None:
    check = load_script()
    findings: list[str] = []
    check.check_graph_key_casing(f"$blob.{spelling}", findings)
    assert any(spelling in f for f in findings)


def test_camel_case_graph_keys_required() -> None:
    check = load_script()
    findings: list[str] = []
    check.check_graph_key_casing(
        "$__graph.tenantId $__graph.clientId $__graph.clientSecret", findings
    )
    assert findings == []


def test_aws_txt_fallback_is_rejected() -> None:
    check = load_script()
    findings: list[str] = []
    check.check_no_aws_txt_fallback('Get-Content "$HOME\\.aws\\SOME_KEY.txt"', findings)
    assert any("TASK-756" in f for f in findings)
