#!/usr/bin/env python3
"""Workstation secrets-loader drift check.

Detects a workstation whose `~/.secrets-env.staging.ps1` did NOT come from
`scripts/bootstrap-windows-secrets.py`. A hand-rolled or agent-written loader
can read the right secret and still wire it wrong.

Why this exists (2026-08-13): the Windows workstation `taylo` ran a loader that
no committed source generates. It probed `tenant_id` / `MICROSOFT_GRAPH_TENANT_ID`
while `plx/prod/m365/cursor-graph/v1` stores camelCase `tenantId`, so every Graph
variable came back empty. It also reintroduced `~/.aws/*.txt` credential
fallbacks that TASK-756 banned after the 2026-07-26 outage. Nothing detected
either problem: the generator was correct, the secret was correct, and only the
copy on that one machine was wrong.

Checks (on the loader at $HOME/.secrets-env.staging.ps1 unless --loader given):
  1. Provenance — the generated header line is present.
  2. TASK-756 — no `~/.aws` credential-file fallbacks.
  3. Graph key casing — reads camelCase tenantId/clientId/clientSecret, and
     never the snake_case or SCREAMING_CASE spellings the secret does not use.
  4. Matched set — all three Graph values come from one secret id.
  5. Byte parity (--strict) — sha256 equals freshly generated output.

Run on a workstation:
    python scripts/check-workstation-loader-drift.py
    python scripts/check-workstation-loader-drift.py --strict   # needs AWS read

Exit codes: 0 — clean, 1 — drift found, 2 — loader missing.

This script never prints secret values. It reports structure only.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "bootstrap-windows-secrets.py"

DEFAULT_LOADER = Path.home() / ".secrets-env.staging.ps1"

GENERATED_HEADER = "Generated by scripts/bootstrap-windows-secrets.py"
CURSOR_GRAPH_SECRET_ID = "plx/prod/m365/cursor-graph/v1"

# The secret stores camelCase. Any loader reading these spellings silently
# produces empty Graph credentials.
FORBIDDEN_KEY_SPELLINGS = [
    "tenant_id",
    "client_id",
    "client_secret",
    "AZURE_TENANT_ID",
    "AZURE_CLIENT_ID",
    "AZURE_CLIENT_SECRET",
    "MICROSOFT_GRAPH_TENANT_ID",
    "MICROSOFT_GRAPH_CLIENT_ID",
    "MICROSOFT_GRAPH_CLIENT_SECRET",
]

REQUIRED_CAMEL_KEYS = ("tenantId", "clientId", "clientSecret")

# TASK-756: the loader must never fall back to credential text files.
AWS_TXT_FALLBACK = re.compile(r"\.aws[\\/][A-Za-z_0-9]+\.txt")


def _fail(findings: list[str], msg: str) -> None:
    findings.append(msg)


def check_provenance(text: str, findings: list[str]) -> None:
    if GENERATED_HEADER not in text:
        _fail(
            findings,
            "provenance: loader is missing the generated header "
            f"({GENERATED_HEADER!r}). It was not produced by the committed "
            "generator — regenerate it with scripts/bootstrap-windows-secrets.py.",
        )


def check_no_aws_txt_fallback(text: str, findings: list[str]) -> None:
    hits = sorted(set(AWS_TXT_FALLBACK.findall(text)))
    if hits:
        _fail(
            findings,
            "TASK-756: loader reads credential text files under ~/.aws "
            f"({', '.join(hits)}). Secrets Manager is the only allowed source.",
        )
    if "Read-SecretFile" in text:
        _fail(
            findings,
            "TASK-756: loader defines/uses Read-SecretFile, the ~/.aws "
            "text-file fallback banned after the 2026-07-26 Graph outage.",
        )


def check_graph_key_casing(text: str, findings: list[str]) -> None:
    """The Graph JSON is read by camelCase key only."""
    # Find every property read off a JSON blob: $var.someKey
    read_keys = set(re.findall(r"\$\w+\.([A-Za-z_][A-Za-z_0-9]*)", text))

    for key in REQUIRED_CAMEL_KEYS:
        if key not in read_keys:
            _fail(
                findings,
                f"graph casing: loader never reads .{key} from the secret. "
                f"{CURSOR_GRAPH_SECRET_ID} stores camelCase "
                f"{'/'.join(REQUIRED_CAMEL_KEYS)}.",
            )

    # Reading a spelling the secret does not contain yields an empty value.
    bad = sorted(k for k in read_keys if k in FORBIDDEN_KEY_SPELLINGS)
    if bad:
        _fail(
            findings,
            "graph casing: loader reads JSON key(s) the secret does not "
            f"contain ({', '.join(bad)}) — these resolve to empty. "
            f"Use {'/'.join(REQUIRED_CAMEL_KEYS)}.",
        )


def strip_comments(text: str) -> str:
    """Drop PowerShell comment lines.

    The generated loader documents the rule it follows ("Do not substitute
    prod/ec2-secrets Graph keys"), so a naive substring scan flags a correct
    file. Only executable lines are evidence of what a loader actually does.
    """
    kept = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        kept.append(line.split(" #", 1)[0] if " #" in line else line)
    return "\n".join(kept)


def check_matched_set(code: str, findings: list[str]) -> None:
    if CURSOR_GRAPH_SECRET_ID not in code:
        _fail(
            findings,
            f"matched set: loader does not reference {CURSOR_GRAPH_SECRET_ID}. "
            "Graph tenant/client/secret must come from that one secret.",
        )
    # Only a real fetch of ec2-secrets matters, not a comment about it.
    for m in re.finditer(r"--secret-id\s+(\S+)", code):
        secret_id = m.group(1).strip("'\"")
        if "ec2-secrets" in secret_id:
            window = code[m.start() : m.start() + 400]
            if "GRAPH" in window.upper() or "graph" in window:
                _fail(
                    findings,
                    "matched set: loader fetches Graph values from "
                    f"{secret_id} — that is a different app (Vinces MCP).",
                )


def check_byte_parity(loader: Path, findings: list[str]) -> None:
    """Regenerate into a scratch HOME and compare sha256."""
    if not GENERATOR.exists():
        _fail(findings, f"parity: generator not found at {GENERATOR}")
        return

    with tempfile.TemporaryDirectory() as tmp:
        env = dict(os.environ)
        env["HOME"] = tmp
        env["USERPROFILE"] = tmp
        proc = subprocess.run(
            [sys.executable, str(GENERATOR)],
            env=env,
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            _fail(
                findings,
                "parity: could not run the generator "
                f"(exit {proc.returncode}). Needs AWS Secrets Manager read "
                "access. Stderr: " + proc.stderr.strip()[:200],
            )
            return

        fresh = Path(tmp) / ".secrets-env.staging.ps1"
        if not fresh.exists():
            _fail(findings, "parity: generator produced no staging loader")
            return

        want = hashlib.sha256(fresh.read_bytes()).hexdigest()
        got = hashlib.sha256(loader.read_bytes()).hexdigest()
        if want != got:
            _fail(
                findings,
                f"parity: loader sha256 {got[:16]}… does not match freshly "
                f"generated {want[:16]}…. Regenerate the loader.",
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--loader",
        type=Path,
        default=DEFAULT_LOADER,
        help="path to the loader (default: ~/.secrets-env.staging.ps1)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="also require byte-for-byte parity with freshly generated output",
    )
    args = parser.parse_args()

    loader: Path = args.loader
    if not loader.exists():
        print(f"SKIP: no loader at {loader}")
        print("This host has no PLX workstation loader. Nothing to check.")
        return 2

    text = loader.read_text(encoding="utf-8", errors="replace")
    code = strip_comments(text)

    findings: list[str] = []
    check_provenance(text, findings)
    check_no_aws_txt_fallback(code, findings)
    check_graph_key_casing(code, findings)
    check_matched_set(code, findings)
    if args.strict:
        check_byte_parity(loader, findings)

    print(f"workstation loader drift check: {loader}")
    if not findings:
        print("OK: loader matches the committed generator contract.")
        return 0

    print(f"DRIFT: {len(findings)} finding(s)\n")
    for i, f in enumerate(findings, 1):
        print(f"  {i}. {f}")
    print(
        "\nFix: run `python scripts/bootstrap-windows-secrets.py` on the "
        "affected workstation to regenerate the loader from Secrets Manager."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
