#!/usr/bin/env python3
"""Generate the metadata-only GitHub routing proposal workflow.

The workflow intentionally uses only GitHub event metadata and the pull-request
files API.  It never checks out or executes pull-request content.

Usage:
    python scripts/generate-routing-workflow.py
    python scripts/generate-routing-workflow.py --check
    python scripts/generate-routing-workflow.py --emit
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_PATH = ROOT / ".github" / "workflows" / "mc-routing-metadata.yml"
FORBIDDEN_PATTERNS = (
    "actions/checkout",
    "actions/cache",
    "actions/setup-",
    "cache:",
    "pull_request_target",
    "run:",
    "npm ",
    "pip ",
    "pnpm ",
    "yarn ",
    "docker ",
    "git checkout",
    "restore-cache",
    "restore-keys",
    "save-cache",
)

WORKFLOW = r"""# Generated by scripts/generate-routing-workflow.py. DO NOT EDIT.
# Metadata-only routing proposal: no checkout or pull-request code execution.
name: MC Routing Metadata

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  propose-routing:
    name: Propose routing from pull request metadata
    if: ${{ vars.PLX_MC_ROUTING_METADATA_ENABLED == '1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send metadata-only routing proposal to Mission Control
        uses: actions/github-script@v7
        env:
          MC_BASE_URL: ${{ vars.PLX_MC_BASE_URL || secrets.PLX_MC_BASE_URL }}
        with:
          github-token: ${{ github.token }}
          script: |
            async function writeSafeSummary(message, deepLink) {
              try {
                core.summary.addHeading("MC Routing Metadata").addRaw(message);
                if (deepLink) {
                  core.summary.addEOL().addLink("Open Mission Control", deepLink);
                }
                await core.summary.write();
              } catch {
                core.warning("Mission Control routing summary could not be written.");
              }
            }

            function validateSuggestionDeepLink(value) {
              if (typeof value !== "string") return null;
              try {
                const parsedDeepLink = new URL(value);
                const proposalValues = parsedDeepLink.searchParams.getAll("proposal");
                const hasUnexpectedQuery = [...parsedDeepLink.searchParams.keys()].some(
                  (key) => key !== "proposal"
                );
                if (
                  parsedDeepLink.protocol !== "https:" ||
                  parsedDeepLink.host !== "mc.plxcustomer.io" ||
                  parsedDeepLink.origin !== "https://mc.plxcustomer.io" ||
                  parsedDeepLink.username ||
                  parsedDeepLink.password ||
                  parsedDeepLink.pathname !== "/routing" ||
                  parsedDeepLink.hash ||
                  hasUnexpectedQuery ||
                  proposalValues.length !== 1 ||
                  !/^rpp_[A-Za-z0-9._:-]+$/.test(proposalValues[0])
                ) {
                  return null;
                }
                return value;
              } catch {
                return null;
              }
            }

            const configuredBaseUrl = process.env.MC_BASE_URL;
            let baseUrl;
            try {
              if (
                configuredBaseUrl !== "https://mc.plxcustomer.io" &&
                configuredBaseUrl !== "https://mc.plxcustomer.io/"
              ) {
                throw new Error("unapproved destination");
              }
              const parsedBaseUrl = new URL(configuredBaseUrl);
              if (
                parsedBaseUrl.protocol !== "https:" ||
                parsedBaseUrl.host !== "mc.plxcustomer.io" ||
                parsedBaseUrl.origin !== "https://mc.plxcustomer.io" ||
                parsedBaseUrl.username ||
                parsedBaseUrl.password ||
                parsedBaseUrl.pathname !== "/" ||
                parsedBaseUrl.search ||
                parsedBaseUrl.hash
              ) {
                throw new Error("unapproved destination");
              }
              baseUrl = parsedBaseUrl.origin;
            } catch {
              core.warning("Mission Control routing destination is unavailable; metadata skipped.");
              await writeSafeSummary("Routing metadata was skipped because its destination is unavailable.");
              return;
            }

            const pr = context.payload.pull_request;
            const sourceRepository = pr.head.repo;
            const targetRepository = context.payload.repository;
            if (
              !sourceRepository ||
              sourceRepository.id !== targetRepository.id ||
              sourceRepository.full_name !== targetRepository.full_name
            ) {
              core.warning("Routing metadata skipped for an untrusted pull request source.");
              await writeSafeSummary("Routing metadata was skipped for an untrusted pull request source.");
              return;
            }

            const automationLogins = [
              context.actor,
              pr.user?.login,
              context.payload.sender?.login,
            ];
            if (automationLogins.includes("dependabot[bot]")) {
              core.warning("Routing metadata skipped for untrusted automation.");
              await writeSafeSummary("Routing metadata was skipped for untrusted automation.");
              return;
            }

            let files;
            try {
              files = await github.paginate(github.rest.pulls.listFiles, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                per_page: 100,
              });
            } catch {
              core.warning("Pull request metadata could not be read; routing skipped.");
              await writeSafeSummary("Routing metadata could not be read and was not sent.");
              return;
            }

            let oidcToken;
            try {
              oidcToken = await core.getIDToken("plx-mc-compliance-verify");
            } catch {
              core.warning("GitHub OIDC is unavailable; routing metadata skipped.");
              await writeSafeSummary("Routing metadata was skipped because GitHub OIDC is unavailable.");
              return;
            }

            const payload = {
              repository: `${context.repo.owner}/${context.repo.repo}`,
              repositoryId: context.payload.repository.id,
              eventName: context.eventName,
              action: context.payload.action,
              prNumber: pr.number,
              headSha: pr.head.sha,
              merged: pr.merged === true,
              // GitHub OIDC binds pull_request jobs to GITHUB_SHA. MC uses this
              // only as an authentication alternate, never as persisted merge evidence.
              mergeSha: process.env.GITHUB_SHA || null,
              headRef: pr.head.ref,
              baseBranch: pr.base.ref,
              sourceBranch: pr.head.ref,
              title: pr.title,
              body: pr.body || "",
              labels: pr.labels.map((label) => label.name),
              changedPaths: files.map((file) => file.filename),
              author: pr.user.login,
              workflowRef: process.env.GITHUB_WORKFLOW_REF,
            };

            let response;
            try {
              response = await fetch(`${baseUrl}/api/routing/propose`, {
                method: "POST",
                headers: {
                  authorization: `Bearer ${oidcToken}`,
                  "content-type": "application/json",
                },
                body: JSON.stringify(payload),
                signal: AbortSignal.timeout(20_000),
              });
            } catch {
              core.warning("Mission Control routing transport failed; delivery remains advisory.");
              await writeSafeSummary("Routing metadata could not be delivered; compliance is unaffected.");
              return;
            }

            const result = await response.json().catch(() => ({}));
            if (!response.ok) {
              core.warning("Mission Control routing did not accept the metadata; delivery remains advisory.");
              await writeSafeSummary("Routing metadata was not accepted; compliance is unaffected.");
              return;
            }

            if (
              result.data?.effectiveMode === "suggestion" &&
              typeof result.data?.deepLink === "string"
            ) {
              const validatedDeepLink = validateSuggestionDeepLink(result.data.deepLink);
              if (!validatedDeepLink) {
                core.warning("Mission Control returned an invalid routing link; no link was shown.");
                await writeSafeSummary("Pull request metadata was recorded by Mission Control.");
                return;
              }
              await writeSafeSummary("An MC suggestion is ready.", validatedDeepLink);
              return;
            }
            await writeSafeSummary("Pull request metadata was recorded by Mission Control.");
"""


def validate_security_contract(workflow: str) -> None:
    """Reject workflow constructs that could execute pull-request content."""
    unsafe = [pattern for pattern in FORBIDDEN_PATTERNS if pattern in workflow.lower()]
    if unsafe:
        raise ValueError(
            "routing workflow is not metadata-only; forbidden patterns: "
            + ", ".join(unsafe)
        )


def main() -> int:
    expected = WORKFLOW
    try:
        validate_security_contract(expected)
    except ValueError as error:
        print(f"ROUTING WORKFLOW SECURITY CONTRACT FAILED — {error}", file=sys.stderr)
        return 1

    if "--emit" in sys.argv[1:]:
        sys.stdout.write(expected)
        return 0

    if "--check" in sys.argv[1:]:
        current = (
            CANONICAL_PATH.read_text(encoding="utf-8")
            if CANONICAL_PATH.exists()
            else ""
        )
        if current != expected:
            print(
                "ROUTING WORKFLOW DRIFT — .github/workflows/mc-routing-metadata.yml "
                "does not match the generator source.",
                file=sys.stderr,
            )
            print("Fix: python scripts/generate-routing-workflow.py", file=sys.stderr)
            return 1
        print("routing workflow aligned with generator source")
        return 0

    CANONICAL_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {CANONICAL_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
